### ISSUE TITLE
Time stamps and unique IDs

### ISSUE THREAD

**Issue by peekpt** [hivedb/hive#118]
Time stamps created and modified on each HiveObject.
Unique ids for each HiveObject;

Since it's a common thing to use time stamps in databases it will be awesome to have this features ready by default
Having Time Stamps natively on each HiveObject (created and modified) returning a DateTime object.
A unique object ID which could be easily created with:
``` int uid = DateTime.now().millisecondsSinceEpoch;```

So we can do things like:
 sortByDate 
 findById->   box.values.firstWhere((o)=o.uid => foo)
deleteById

I know we have the Key option but are they really unique?

edit : I forgot to say uid's are constant no change during editing, even you move the object in the index.  Also the uids are a good way of linking objects to another boxes and you don't care about its type. 
Other approach : having the id String with this pattern BOXNAME#UID and be able to do Hive.deleteById(int uid)

` Hive.box(uid.split('#')[0]).values.firstWhere((obj)=>obj.uid == uid).delete();`

**Comment by leisim** [comment]
I'm not sure about this. I considered it when I implemented integer keys and ultimately I decided it would be better if you just do the following:
```dart
@HiveType()
class SomeObject extends HiveObject {
  @HiveField(0)
  String name;

  DateTime time;

  @HiveField(1)
  DateTime get dbTime => DateTime.now()

  @HiveType(1)
  set dbTime(DateTime dbTime) {
    time = dbTime;
  }
}
```

The problem with using time as key is that milliseconds are not unique. Hive can do many transactions in a single millisecond. Even microseconds would need a check. Microseconds are also not supported in JavaScript because they do not fit in a 64 bit double.

If you need every object to have a time, I suggest you use the class above as mixin.

**Comment by peekpt** [comment]
Oh, I see, I didn't thought about creating multiple objects in a row, and I think appending a random number to the ID will not help also in this situation because it's expensive. The uid generators never tried...

**Comment by Comevius** [comment]
Ulid is a good solution for a unique ID. It has a 48 bit time (won't run out of space until the year 10889) and 80 bit random part. It can be canonically encoded as a 26 character, lexicographically shortable string.

https://github.com/ulid/spec

Please note that the [ulid package](https://pub.dev/packages/ulid) on pub.dev is not compliant with the specification (it encodes lowercase, instead of uppercase characters).

**Comment by peekpt** [comment]
The problem here is not generating the uids. Having it run fast is the problem.

**Comment by Comevius** [comment]
> Having it run fast is the problem.

If you need tens of thousands of unique identifiers each second you can try to amortize the cost by pre-generating random numbers.

Writing and (and later reading, compacting) that much entries with Hive would be probably slow though.

> and for the web like leisim said it must fit a 64 bit double

Hive is limited to 32-bit unsigned int and 255-character String keys. 64-bit doubles would at least give us 53-bit int space, but that's not the case with Hive. It needs the key to be less than 4294967295 (should be less than 4294967296, because 4294967295 or 2^32-1 should be the maximum).
