### ISSUE TITLE
Performance: Many boxes and few keys vs. One box and many keys?

### ISSUE THREAD

**Issue by frank06** [hivedb/hive#146]
**Question**

I am working on an app that will have 30 or even more models / types.  I was planning to use one box per type, which means that at runtime possibly most boxes will get opened simultaneously.

I would use one type adapter per type, with the binary serialization format.

Alternatively, I could have all keys in the same box and namespace them with prefixes (e.g. `Post-43`) and use a JSON / `Map<String, dynamic>` serialization format.

What is the recommended approach in terms of performance?   Are queries still part of the roadmap, if so, how would each approach fare in when queries arrive?

**Comment by leisim** [comment]
The answer depends on multiple factors:
**Normal boxes** load all the entries into memory when they are opened for the first time. In theory, a single box should have the best startup time. Multiple boxes will have multiple files which can all be written simultaneously. So write performance might be better when you have multiple boxes.

**Lazy boxes** will read all the keys when they are opened.

For both types the performance differences between a single box and multiple boxes are very small so I suggest to use individual boxes for each type.

I still work on queries. They will not support a "join" between boxes.

**Comment by frank06** [comment]
That makes sense, I appreciate your response @leisim, it helps now in the design phase. I will start opening one box per type and eventually make stress tests.

> There will also be support for "backlinks" (lists of links to another box) very soon e.g. a user entry can have a list of posts which are stored in another box.

Ah, that would be seriously awesome! We would definitely make use of it, as obviously most of our models are linked. Any branch I can follow for updates?

All in all, fantastic work. Thank you!

**Comment by leisim** [comment]
> Any branch I can follow for updates?

The feature is already in the master branch and in `v1.2.0-dev` but I did not document it because I'm still not sure about the correct approach.

There are two options that I found:
1. The list only saves the name of the box of the "remote" objects and the keys. Every time the user accesses an element of the list, it is loaded from the box 

2. The list is loaded entirely when the fist item is accessed. This will make subsequent accesses much faster but it also adds overhead because the list needs to be updated for example when one of its object is removed in the remote box. This leads to very complex code and also complicates the usage.

I'm not sure if the performance improvement is worth the cost...

**Comment by frank06** [comment]
If the API of (1) and (2) are similar enough I think starting by (1) would allow you to deliver this feature faster, and get usage feedback from the community earlier.

I believe we (library cients) can experiment with caching in custom type adapters, if needed. Further optimizations like (2) could be included directly in Hive based on patterns found with usage in the community?

**Comment by leisim** [comment]
Yes I agree. Maybe we even need both types in the long run but I also think we should start with (1).
