### ISSUE TITLE
1.3 breaks projects that include hive with carat notation in pubspec

### ISSUE THREAD

**Issue by RabbitKabong** [hivedb/hive#167]
**Steps to Reproduce**
1) Use Hive with generated code from the older API (1.2 or less).
2) Include `hive` in pubspec.yaml using carat notation (^): `hive: ^1.2.0`.
3) Run `flutter packages get`, which upgrades Hive to 1.3.
4) Build errors, since my code doesn't use the new 1.3 API:

When I call `Hive.registerAdapter()`:
```
Too many positional arguments: 1 expected, but 2 found.
Try removing the extra arguments.
```

Declaration of my generated `TypeAdapter`:
```
Missing concrete implementation of 'getter TypeAdapter.typeId'.
Try implementing the missing method, or make the class abstract.
```

The best that I understand, since carat notation is shorthand for `>=1.2.0 <2.0.0`, 1.3 is still "allowed" when `packages get` resolves the package version; but 1.3 breaks the API.  It can be fixed by requiring the exact version (i.e. `hive:  1.2.0` in the pubspec file), but it seems like the API break should mean v2.0, right?

**Version**
 - Platform: iOS, Android
 - Flutter version: 1.12.13+hotfix.5
 - Hive version: 1.2

**Comment by leisim** [comment]
Thanks for letting me know. I thought `^1.2.0` is shorthand for `>=1.2.0 <1.3.0`.

In the future I will create a new major version for changes that are likely breaking for many users.

**Comment by gogreen42** [comment]
Same problem

**Comment by leisim** [comment]
@gogreen42

Just use
```yaml
hive: 1.2.0
```

and you should be fine.

**Comment by Mani06101999** [comment]
thanks a lot ,issue solved 

dont use carot notation " ^"  use hive: 1.2.0
problem solved

**Comment by WizSan** [comment]
I'm having the same problem here.
 
I'm a beginner in flutter, I'm wondering why it is still error, I already follow about what should be the remedy. If I remove the carat notation and type flutter clean, and  flutter pub get or just flutter pub get, it gives me this error.

Because every version of flutter_test from sdk depends on path 1.8.0-nullsafety and hive >=0.4.1 <1.4.0-dev depends on path >=1.6.0 <1.7.0, flutter_test from sdk is incompatible with hive >=0.4.1 <1.4.0-dev.
Running "flutter pub get" in basicDB...                               So, because basicDB depends on both hive 1.3.0 and flutter_test any from sdk, version solving failed.
Running "flutter pub get" in basicDB...                                       
pub get failed (1; So, because basicDB depends on both hive 1.3.0 and
flutter_test any from sdk, version solving failed.)

I have no choice but to put that notation again.
I've already done about flutter packages get
still the type adapter is error.

**Comment by kiasNostieDev** [comment]
Duplicate of #290 

I used the decorator like this @HiveType(typeId: 0)
(The Hive docs need to be updated, BTW. The typeId argument isn't mentioned.)

Fill up the missing override typeId: 

  @override
  final typeId = 0;

Don't forget to run flutter pub run build_runner build to generate the code.
