### ISSUE TITLE
TypeId limit

### ISSUE THREAD

**Issue by carmas123** [hivedb/hive#188]
Hi, I try to use this library for my project but I see that there is a limit about typeId for registered adapter. Please can you explain me if now I start to use this lib why there is this limit?
If in the future I need to define more than 224 typeId, how can I bypass this problem?

My best regards.

**Comment by marcelgarus** [comment]
There is a limit because type ids are currently encoded in a single byte, so there are 256 bytes possible.
Internally, Hive uses some reserved type ids for primitive types like `String`, `int`, `HiveList` and more, so there are 224 left for you.

Currently, the only way to bypass this problem I know about is to use multiple hive instances and register different adapters on them aka do `final HiveA = HiveImpl();` and `final HiveB = HiveImpl();` and then call `HiveA.registerAdapter(…)`.  
Admittedly, this is an ugly workaround.

The serializer is currently redesigned and if there are incompatible changes anyways, I think it wouldn't hurt to make type ids two or maybe even three bytes long, allowing for 65536 or 16777216 types, respectively.

**Comment by carmas123** [comment]
I think that 65536 isn't a limitation and is a good limit :)
Regards

**Comment by leisim** [comment]
I'm still not entirely convinced to increase the limit. I have never seen an app that came even close to the limit.

**Comment by cbalmeida** [comment]
I have a project with more than 1,000 different "tables" and we're using SQLite... We have made some tests with Hive and it looks very good! But with this typeId limit, we can go any further! Guys... it is 2021!! We got memory, we got processing power, we got devices with so much "room".... but some ppl insist in living in a world of 8 bit limits! You can NEVER (I mean "EVER") impose a limit of at least 65536 of something like this! It is so frustrating! Wake up!

**Comment by carmas123** [comment]
What do you do into an app with more than 1000 tables???
Are you sure that you need all of these?

**Comment by marzoukali** [comment]
This is the only reason why I didn't choose Hive for my project

**Comment by dhanushnagraj88** [comment]
> I'm still not entirely convinced to increase the limit. I have never seen an app that came even close to the limit.

Please consider increasing the limit at least now. I love how simple Hive is to use but the limit of 256 TypeIds is very much a disadvantage for my app since i have a lot of nested objects and the 256 Ids limit will be of no use. Please consider changing it

**Comment by dhanushnagraj88** [comment]
Can anyone help me on how i can overcome the TypeId limit?
It seems i cannot access HiveImple for creating multiple instances so that workaround is not working for me!!!
