### ISSUE TITLE
[Feature Request] Locate method

### ISSUE THREAD

**Issue by MoacirSchmidt** [hivedb/hive#209]
Please provide a box.locate(key) or box.getNearest(key) or box.findNearest(key) method that returns the index of the key if it exists or the next one if not (-1 if there is no one next).

It would be very useful if you need to interact over a subset of the box without need to use dart's "where"

I think it will solve a good part of the needs for specific queries

Thank you very  much for you excellent library!

P.S. I have checked the implementation and figured out that getAt(index) is not O(1). So I think we also need getNext and getPrior methods that can be implemented as O(1).

Thanks again!

**Comment by leisim** [comment]
> Please provide a box.locate(key) or box.getNearest(key) or box.findNearest(key) method that returns the index of the key if it exists or the next one if not

Could you please describe your use case for this method?

>  I have checked the implementation and figured out that getAt(index) is not O(1)

Hive uses and indexable skip list which makes random access by key or index O(log n).

> So I think we also need getNext and getPrior methods that can be implemented as O(1).

I don't think this is possible without exposing the `Node` class from the indexable skip list. Getting the next node is indeed O(1) because skip lists are just extended linked lists but if you just have the key or index and not the `Node` it is O(log n).

The `box.values` iterable has O(1) for getting the next element and if there is a use case for that maybe we could expose something like `box.valuesAfterKey(key)` or `box.valuesAfterIndex(index)` which would have O(log n) for the first access and O(1) for getting the next element.

**Comment by MoacirSchmidt** [comment]
> 
> Could you please describe your use case for this method?
> 
I have an infinite scroll widget which may have more than 10.000 items. I would not like to read all items but read them as user scrolls down the UI. It would be similar to a SQL query like "select message from messages where messageId > :oldestMessageId".

> we could expose something like `box.valuesAfterKey(key)` or `box.valuesAfterIndex(index)` which would have O(log n) for the first access and O(1) for getting the next element.

That would be PERFECT for my needs!

Thank you very much for  your attention!

**Comment by leisim** [comment]
> That would be PERFECT for my needs!

 Okay, I like the idea. This method will be part of v1.4.0 which should be released within the next two weeks...

**Comment by MoacirSchmidt** [comment]
> 
> Okay, I like the idea. This method will be part of v1.4.0 which should be released within the next two weeks...
>
Comment from iterator.dart:
```
 * The `Iterator` is initially positioned before the first element.
 * Before accessing the first element the iterator must thus be advanced using
 * [moveNext] to point to the first element.
```
This may complicate things ...

**Comment by leisim** [comment]
The methods would return an `Iterable` not `Iterator` it can be used almost like a list...

**Comment by leisim** [comment]
There is now a `box.betweenKeys()` method which allows you to get the values in the specified range.
