### ISSUE TITLE
Constructor of class E is called on openBox<E>()

### ISSUE THREAD

**Issue by kaboc** [hivedb/hive#217]
**Question**
Flow and desired behaviour:

1. A box for `SomeModel` is opened.
    * `final box = await Hive.openBox<SomeModel>('model');`
2. The box is passed to a repository.
3. The constructor of `SomeModel` is called after all the above preparations.

Against my expectation, the constructor of `SomeModel` is called at the step 1. Is it a bug? If not so, is there any way to prevent the unwanted call?

**Code sample**
You can reproduce a similar behaviour by slightly changing the sample code in the [Relationships](https://docs.hivedb.dev/#/custom-objects/relationships) document.

```dart
class Person extends HiveObject {
  ...
  Person(this.name);
  ...
}
```

Change the constructor as below so you can see it called.

```dart
class Person extends HiveObject {
  ...
  Person(this.name) {
    print(name);
  }
  ...
}
```

If you run it only once, three names are output as expected from the code. 

```
Mario
Luna
Alex
```

However, if you run more times, six names are output; the first three are printed at the point of `openBox()`.

```
Mario
Luna
Alex
Mario
Luna
Alex
```

In fact, this is not exactly the same as my actual case. The constructor seems to be called even at the first execution, with nothing (`null`) passed in.

**Version**
 - Platform: Windows
 - Flutter version: N/A
 - Hive version: 1.3.0

**Comment by leisim** [comment]
> Against my expectation, the constructor of SomeModel is called at the step 1. Is it a bug?

It is expected behavior and not a bug. Normal (non-lazy) boxes load all their keys and values into memory when the box is first opened.

Because there is no data in the box you see three outputs (from the three constructor calls in the sample code). All subsequent runs already have three persons in the box so the constructor is called six times.

If you don't want the objects to be loaded into memory when you open the box, you can use a `LazyBox`.

**Comment by kaboc** [comment]
I'm sorry for my misunderstanding and having bothered you.
I'll have a look at `LazyBox`. Thank you very much!
