### ISSUE TITLE
BoxEvent value is null when watching a LazyBox

### ISSUE THREAD

**Issue by adiospace** [hivedb/hive#265]
**Question**
When watching a lazy box by key, event.value is null. Is this the correct behaviour? 

**Code sample**
```dart
await Hive.openLazyBox<Game>('games');
LazyBox<Game> game = await Hive.lazyBox('games').get('id');

game.watch(key: game.id).listen((e) { print(e.value == null);});

game.nextLevel++;
game.save();

```

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: 1.12.13+hotfix.8
 - Hive version: ^1.4.1+1

**Comment by dop3ch3f** [comment]
Seems to me like normal behavior. IMHO game.watch().listen is like the default stream subscription so it should behave like one and if its initialized without data its going to return null.

**Comment by leisim** [comment]
> When watching a lazy box by key, event.value is null. Is this the correct behaviour?

I don't think it is. Does this still happen?

**Comment by JayDev43** [comment]
Hi, 

This has just happened to me too. 

Debugging the code, I think the problem is that in LazyBoxImpl.putAll() the frame is being converted to a lazy Frame using frame.toLazy() and is then passed into the keystore.insert() method. When that frame makes it the the notifier as its a lazy Frame the value is null and this is what is then being sent out onto the stream. 

Hope that helps solve the problem.

**Comment by kyleschlosser** [comment]
This just happened to me too. I am on `^1.5.0-pre`.

**Comment by Abdelazeem777** [comment]
I am facing the same problem here with `^1.4.4+1`.
Also, I did some debugging and I think the problem is with `frame.toLazy()` because it returns a frame with **null** value.

**Comment by dkunzler** [comment]
I can confirm the problem with `1.6.0-nullsafety.2`
