### ISSUE TITLE
HiveError: Cannot read, unknown typeId: 32. Did you forget to register an adapter?

### ISSUE THREAD

**Issue by dominikkeller** [hivedb/hive#269]
When I try start the app this error always appears:
HiveError: Cannot read, unknown typeId: 32. Did you forget to register an adapter?

My Hivetype:
```
import 'package:flutter/cupertino.dart';
import 'package:hive/hive.dart';

part 'auth_token_response_model.g.dart';

@HiveType(typeId: 1)
class  AuthTokenResponseModel {

  AuthTokenResponseModel({@required this.accessToken, @required this.refreshToken,  @required this.accessTokenExpirationDateTime,  @required this.idToken,  @required this.tokenType});

  @HiveField(0)
  final String accessToken;
  @HiveField(1)
  final String refreshToken;
  @HiveField(2)
  final DateTime accessTokenExpirationDateTime;
  @HiveField(3)
  final String idToken;
  @HiveField(4)
  final String tokenType;
}
```

g.dart file: 
```// GENERATED CODE - DO NOT MODIFY BY HAND
part of 'auth_token_response_model.dart';
// **************************************************************************
// TypeAdapterGenerator
// **************************************************************************

class AuthTokenResponseModelAdapter
    extends TypeAdapter<AuthTokenResponseModel> {
  @override
  AuthTokenResponseModel read(BinaryReader reader) {
    var numOfFields = reader.readByte();
    var fields = <int, dynamic>{
      for (var i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return AuthTokenResponseModel(
      accessToken: fields[0] as String,
      refreshToken: fields[1] as String,
      accessTokenExpirationDateTime: fields[2] as DateTime,
      idToken: fields[3] as String,
      tokenType: fields[4] as String,
    );
  }
  @override
  void write(BinaryWriter writer, AuthTokenResponseModel obj) {
    writer
      ..writeByte(5)
      ..writeByte(0)
      ..write(obj.accessToken)
      ..writeByte(1)
      ..write(obj.refreshToken)
      ..writeByte(2)
      ..write(obj.accessTokenExpirationDateTime)
      ..writeByte(3)
      ..write(obj.idToken)
      ..writeByte(4)
      ..write(obj.tokenType);
  }
  @override
  int get typeId => 1;
}
```

Main:
```
await Hive.initFlutter();
    final appDocumentDir = await path_provider.getApplicationDocumentsDirectory();
    Hive.init(appDocumentDir.path);
    Hive.registerAdapter(AuthTokenResponseModelAdapter());
    await HiveService.hiveInit();
```

hiveInit:
```
static Future<Box> hiveInit() async {
    await Hive.openBox('userlogin');
    await Hive.openBox('skipped');
    await  Hive.openBox('lastSearched');
  }
```

**Version**
 - Platform: iOS, Android
 - Flutter version: v1.12.13+hotfix.8
 - Hive version: 
hive: ^1.0.0
hive_flutter: ^0.3.0+2

**Comment by Mravuri96** [comment]
@dominikkeller 
add 
```dart
class AuthTokenResponseModelAdapter
    extends TypeAdapter<AuthTokenResponseModel> {
//Missing 
@override
  final typeId = 1;
//Missing

@override
  AuthTokenResponseModel read(BinaryReader reader) {
...
```
Also Try Changing 

```dart
Hive.registerAdapter(AuthTokenResponseModelAdapter());
```
to 
```dart
Hive.registerAdapter< AuthTokenResponseModel >(AuthTokenResponseModelAdapter());
```

**Comment by shafi49** [comment]
@Mravuri96  thank you so much man, it worked for me.

**Comment by joaovirgili** [comment]
@Mravuri96 this workaround doesn't worked for me. I have typeId from 0 to 33 and the error says: `HiveError: Cannot read, unknown typeId: 69. Did you forget to register an adapter?`

**Comment by Mravuri96** [comment]
> @Mravuri96 this workaround doesn't worked for me. I have typeId from 0 to 33 and the error says: `HiveError: Cannot read, unknown typeId: 69. Did you forget to register an adapter?`
> 
> Any solution? It suddenly happened, I don't know how.

@joaovirgili try updating your packages to their latest versions, if that doesn't work, can you post a minimal reproducible code.

**Comment by joaovirgili** [comment]
> > @Mravuri96 this workaround doesn't worked for me. I have typeId from 0 to 33 and the error says: `HiveError: Cannot read, unknown typeId: 69. Did you forget to register an adapter?`
> > Any solution? It suddenly happened, I don't know how.
> 
> @joaovirgili try updating your packages to their latest versions, if that doesn't work, can you post a minimal reproducible code.

@Mravuri96 
Already done that and the error persists. I guess there's no way to post a reproducible code 'cause it's a huge project , it's not viable but i will try to share some of them.

Flutter doctor:
```Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G73,
    locale en)
[✓] Android toolchain - develop for Android devices (Android SDK
    version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.47.2)
 
[✓] Connected device (1 available)            

• No issues found!
```

Versions:
```
hive: ^1.4.2
hive_generator: ^0.7.0+2
build_runner: ^1.7.4
```

Error stack
```
E/flutter (26676): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: HiveError: Cannot read, unknown typeId: 69. Did you forget to register an adapter?
E/flutter (26676): #0      BinaryReaderImpl.read 
package:hive/…/binary/binary_reader_impl.dart:322
E/flutter (26676): #1      LojaAdapter.read 
package:pepsfield_app_promotores/…/models/rota_diaria_model.g.dart:57
E/flutter (26676): #2      BinaryReaderImpl.read 
package:hive/…/binary/binary_reader_impl.dart:325
E/flutter (26676): #3      BinaryReaderImpl.readMap 
package:hive/…/binary/binary_reader_impl.dart:212
E/flutter (26676): #4      BinaryReaderImpl.read 
package:hive/…/binary/binary_reader_impl.dart:316
E/flutter (26676): #5      RotaDiariaAdapter.read 
package:pepsfield_app_promotores/…/models/rota_diaria_model.g.dart:17
E/flutter (26676): #6      BinaryReaderImpl.read 
package:hive/…/binary/binary_reader_impl.dart:325
E/flutter (26676): #7      BinaryReaderImpl.readFrame 
package:hive/…/binary/binary_reader_impl.dart:273
E/flutter (26676): #8      FrameHelper.framesFromBytes 
package:hive/…/binary/frame_helper.dart:17
E/flutter (26676): #9      FrameIoHelper.framesFromFile 
package:hive/…/io/frame_io_helper.dart:41
E/flutter (26676): <asynchronous suspension>
E/flutter (26676): #10     StorageBackendVm.initialize 
package:hive/…/vm/storage_backend_vm.dart:82
E/flutter (26676): <asynchronous suspension>
E/flutter (26676): #11     BoxBaseImpl.initialize 
package:hive/…/box/box_base_impl.dart:90
E/flutter (26676): #12     HiveImpl._openBox 
package:hive/src/hive_impl.dart:90
E/flutter (26676): <asynchronous suspension>
E/flutter (26676): #13     HiveImpl.openBox 
package:hive/src/hive_impl.dart:111
E/flutter (26676): #14     _LoginControllerBase.initHive 
package:pepsfield_app_promotores/…/login/login_controller.dart:169
E/flutter (26676): <asynchronous suspension>
E/flutter (26676): #15     _LoginControllerBase.init 
package:pepsfield_app_promotores/…/login/login_controller.dart:83
E/flutter (26676): #16     _LoginPageState.initState 
package:pepsfield_app_promotores/…/login/login_page.dart:28
E/flutter (26676): #17     StatefulElement._firstBuild 
package:flutter/…/widgets/framework.dart:4640
E/flutter (26676): #18     ComponentElement.mount 
package:flutter/…/widgets/framework.dart:4476
E/flutter (26676): #19     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3446
E/flutter (26676): #20     Element.updateChild 
package:flutter/…/widgets/framework.dart:3214
E/flutter (26676): #21     ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:4527
E/flutter (26676): #22     StatefulElement.performRebuild 
package:flutter/…/widgets/framework.dart:4675
E/flutter (26676): #23     Element.rebuild 
package:flutter/…/widgets/framework.dart:4218
E/flutter (26676): #24     ComponentElement._firstBuild 
package:flutter/…/widgets/framework.dart:4481
E/flutter (26676): #25     StatefulElement._firstBuild 
package:flutter/…/widgets/framework.dart:4666
E/flutter (26676): #26     ComponentElement.mount 
package:flutter/…/widgets/framework.dart:4476
E/flutter (26676): #27     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3446
E/flutter (26676): #28     Element.updateChild 
package:flutter/…/widgets/framework.dart:3214
E/flutter (26676): #29     ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:4527
E/flutter (26676): #30     Element.rebuild 
package:flutter/…/widgets/framework.dart:4218
E/flutter (26676): #31     ComponentElement._firstBuild 
package:flutter/…/widgets/framework.dart:4481
E/flutter (26676): #32     ComponentElement.mount 
package:flutter/…/widgets/framework.dart:4476
E/flutter (26676): #33     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3446
E/flutter (26676): #34     Element.updateChild 
package:flutter/…/widgets/framework.dart:3214
E/flutter (26676): #35     SingleChildRenderObjectElement.mount 
package:flutter/…/widgets/framework.dart:5830
E/flutter (26676): #36     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3446
E/flutter (26676): #37     Element.updateChild 
package:flutter/…/widgets/framework.dart:3214
E/flutter (26676): #38     SingleChildRenderObjectElement.mount 
package:flutter/…/widgets/framework.dart:5830
E/flutter (26676): #39     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3446
E/flutter (26676): #40     Element.updateChild 
package:flutter/…/widgets/framework.dart:3214
E/flutter (26676): #41     ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:4527
E/flutter (26676): #42     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4
```

Init hive
```
var dir = await getApplicationDocumentsDirectory();
    Hive.init(dir.path);
    Hive.registerAdapter<CountryCode>(CountryCodeAdapter());
    Hive.registerAdapter<CountryOption>(CountryOptionAdapter());
    Hive.registerAdapter<MeuProduto>(MeuProdutoAdapter());
    Hive.registerAdapter<Categoria>(CategoriaAdapter());
    Hive.registerAdapter<Posicao>(PosicaoAdapter());
    Hive.registerAdapter<EnderecoLoja>(EnderecoLojaAdapter());
    Hive.registerAdapter<Info>(InfoAdapter());
    Hive.registerAdapter<Produto>(ProdutoAdapter());
    Hive.registerAdapter<RotaInfo>(RotaInfoAdapter());
    Hive.registerAdapter<CategoriasFoto>(CategoriasFotoAdapter());

    Hive.registerAdapter<RotasMetadata>(RotasMetadataAdapter());
    Hive.registerAdapter<SafeZoneCheck>(SafeZoneCheckAdapter());
    Hive.registerAdapter<Pausa>(PausaAdapter());
    Hive.registerAdapter<SafeZone>(SafeZoneAdapter());
    Hive.registerAdapter<TarefaCheck>(TarefaCheckAdapter());
    Hive.registerAdapter<Tarefa>(TarefaAdapter());
    Hive.registerAdapter<Check>(CheckAdapter());
    Hive.registerAdapter<Loja>(LojaAdapter());
    Hive.registerAdapter<ProdutoRuptura>(ProdutoRupturaAdapter());
    Hive.registerAdapter<TarefaRuptura>(TarefaRupturaAdapter());

    Hive.registerAdapter<ProdutoPreco>(ProdutoPrecoAdapter());
    Hive.registerAdapter<TarefaPreco>(TarefaPrecoAdapter());
    Hive.registerAdapter<TarefaFotos>(TarefaFotosAdapter());
    Hive.registerAdapter<Gondola>(GondolaAdapter());
    Hive.registerAdapter<ProdutoEstoque>(ProdutoEstoqueAdapter());
    Hive.registerAdapter<TarefaEstoque>(TarefaEstoqueAdapter());
    Hive.registerAdapter<Lote>(LoteAdapter());
    Hive.registerAdapter<RotaDiaria>(RotaDiariaAdapter());
    Hive.registerAdapter<PosicaoComTempo>(PosicaoComTempoAdapter());
    Hive.registerAdapter<TarefaGondola>(TarefaGondolaAdapter());

    Hive.registerAdapter<ProdutoGondola>(ProdutoGondolaAdapter());
    Hive.registerAdapter<Deslocamento>(DeslocamentoAdapter());
    Hive.registerAdapter<MarcaConcorrente>(MarcaConcorrenteAdapter());

    await Hive.openBox('user');
    await Hive.openBox('utils');
    await Hive.openBox('preco');
    await Hive.openBox('gondola');
```

The error happens when `user` box is openned, in Loja's adapter generated class:
```
class LojaAdapter extends TypeAdapter<Loja> {
  @override
  final int typeId = 18;

  @override
  Loja read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return Loja(
      checkin: fields[0] as Check,
      checkout: fields[1] as Check,
      cidade: fields[2] as String,
      concluida: fields[3] as bool,
      estado: fields[4] as String,
      estoque: fields[5] as TarefaEstoque,
      fotos: fields[6] as TarefaFotos,
      lojaId: fields[7] as String,
      nomeLoja: fields[8] as String,
      nomeRede: fields[9] as String,
      precos: fields[10] as TarefaPreco,
      redeId: fields[11] as String,
      ruptura: fields[12] as TarefaRuptura,
      safeZone: (fields[13] as List)?.cast<SafeZone>(),
      tarefasCompletas: fields[14] as int,
      tarefasTotais: fields[15] as int,
      gondolas: fields[16] as TarefaGondola,
    );
  }

  @override
  void write(BinaryWriter writer, Loja obj) {
    writer
      ..writeByte(17)
      ..writeByte(0)
      ..write(obj.checkin)
      ..writeByte(1)
      ..write(obj.checkout)
      ..writeByte(2)
      ..write(obj.cidade)
      ..writeByte(3)
      ..write(obj.concluida)
      ..writeByte(4)
      ..write(obj.estado)
      ..writeByte(5)
      ..write(obj.estoque)
      ..writeByte(6)
      ..write(obj.fotos)
      ..writeByte(7)
      ..write(obj.lojaId)
      ..writeByte(8)
      ..write(obj.nomeLoja)
      ..writeByte(9)
      ..write(obj.nomeRede)
      ..writeByte(10)
      ..write(obj.precos)
      ..writeByte(11)
      ..write(obj.redeId)
      ..writeByte(12)
      ..write(obj.ruptura)
      ..writeByte(13)
      ..write(obj.safeZone)
      ..writeByte(14)
      ..write(obj.tarefasCompletas)
      ..writeByte(15)
      ..write(obj.tarefasTotais)
      ..writeByte(16)
      ..write(obj.gondolas);
  }

  @override
  int get hashCode => typeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LojaAdapter &&
          runtimeType == other.runtimeType &&
          typeId == other.typeId;
}
```

**Comment by totalerex** [comment]
I have the same error as in initial post. Initially It was running well today but just after some hot-restart stopped to wor. No code change has been done at the hive part at all.

**Comment by usernamekk** [comment]
I have the same issue.

Unhandled Exception: HiveError: Cannot read, unknown typeId: 32. Did you forget to register an adapter?

**Comment by allobrox** [comment]
Possible solution what worked for me is to register adapters BEFORE calling `await Hive.initFlutter();`

**Comment by TheMisir** [comment]
Possible reasons:

1. You have to register adapter to read/write type. The adapters must be registered before any `openBox` requests. Because openBox uses adapters to read data from the disk.

2. Don't change model typeId after writing the data to the box, otherwise you'll have to remove / clear database from the disk after changing typeId.

**Comment by AdamMusa** [comment]
I solved my problem by doing these **mymodel.deleteFromDisk()**
you should try the same

**Comment by easazade** [comment]
@totalerex  one thing you should always keep in mind is to always register the adapters before opening the box of the entity that the said adapter works with. this will not cause any problem when the box is empty but when the box has some entries. you will get this error. if you hot restart the app and you're getting this error. possibly this is the reason.

**Comment by kaciula** [comment]
This also happened to me and I discovered what the cause was. I was using a box for keeping user preferences, holding various types of objects inside it. I no longer needed a certain type of object so I deleted the object declaration and removed that object adapter from the code. And then it crashed.

I do not know how to proceed. I cannot delete the box because I have other user preferences inside. The only solution is to keep the old object declaration and the adapter. This isn't ideal because I'm keeping old unused code. Any ideas?

**Comment by ashwynh21** [comment]
> 
> 
> @totalerex one thing you should always keep in mind is to always register the adapters before opening the box of the entity that the said adapter works with. this will not cause any problem when the box is empty but when the box has some entries. you will get this error. if you hot restart the app and you're getting this error. possibly this is the reason.
> 
> **Just register all adapters before opening any box**

You were absolutely right, thank you soo much. The trick is to register all your adapters before opening any type of box...

**Comment by lchwe** [comment]
Adding `Hive.ignoreTypeId<YourModel>(0);` after registering the `TypeAdapter` fixed the error `Unhandled Exception: HiveError: Cannot read, unknown typeId: 32. Did you forget to register an adapter?` for me

**Comment by ousvat** [comment]
> Possible solution what worked for me is to register adapters BEFORE calling `await Hive.initFlutter();`

For me worked if I register adapters BEFORE opening any box.

**Comment by gabrielroodriz** [comment]
> Possible solution that worked for me is to register adapters BEFORE calling `await Hive.initFlutter();`

A solution that worked for me

**Comment by dombroks** [comment]
I had this issue when I changed the type of one of my Model attributes, I solved it but re-installing the app from my device. Another similar solution is to delete the model from the disk.

**Comment by Basha0** [comment]
Hey I have kinda the same issue. For me after updating the app(and changes in the Model) I got some issues.

`D/FlutterLocationService(19377): Creating service.
D/FlutterLocationService(19377): Binding to location service.
W/FlutterJNI(19377): FlutterJNI.setRefreshRateFPS called more than once
W/FlutterJNI(19377): FlutterJNI.loadLibrary called more than once
W/FlutterJNI(19377): FlutterJNI.init called more than once
W/FlutterJNI(19377): FlutterJNI.prefetchDefaultFontManager called more than once
E/flutter (19377): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: HiveError: Cannot read, unknown typeId: 33. Did you forget to register an adapter?
E/flutter (19377): #0      BinaryReaderImpl.read (package:hive/src/binary/binary_reader_impl.dart:323)
E/flutter (19377): #1      BinaryReaderImpl.readMap (package:hive/src/binary/binary_reader_impl.dart:212)
E/flutter (19377): #2      BinaryReaderImpl.read (package:hive/src/binary/binary_reader_impl.dart:317)
E/flutter (19377): #3      ProductAdapter.read (package:protector_app/database_models/product.g.dart:17)
E/flutter (19377): #4      BinaryReaderImpl.read (package:hive/src/binary/binary_reader_impl.dart:326)
E/flutter (19377): #5      BinaryReaderImpl.readFrame (package:hive/src/binary/binary_reader_impl.dart:274)
E/flutter (19377): #6      FrameHelper.framesFromBytes (package:hive/src/binary/frame_helper.dart:21)
E/flutter (19377): #7      FrameIoHelper.framesFromFile (package:hive/src/io/frame_io_helper.dart:42)
E/flutter (19377): <asynchronous suspension>
E/flutter (19377): #8      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:86)
E/flutter (19377): <asynchronous suspension>
E/flutter (19377): #9      HiveImpl._openBox (package:hive/src/hive_impl.dart:111)
E/flutter (19377): <asynchronous suspension>
E/flutter (19377): #10     HiveImpl.openBox (package:hive/src/hive_impl.dart:139)
E/flutter (19377): <asynchronous suspension>
E/flutter (19377): #11     HiveService.open (package:protector_app/database/hive_service.dart:42)
E/flutter (19377): <asynchronous suspension>
E/flutter (19377): #12     JSONApi.initialize (package:protector_app/networking/jsonAPI.dart:46)
E/flutter (19377): <asynchronous suspension>
E/flutter (19377): #13     main (package:protector_app/main.dart:30)
E/flutter (19377): <asynchronous suspension>
E/flutter (19377): 
E/flutter (19377): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: HiveError: Cannot read, unknown typeId: 33. Did you forget to register an adapter?
E/flutter (19377): #0      BinaryReaderImpl.read (package:hive/src/binary/binary_reader_impl.dart:323)
E/flutter (19377): #1      BinaryReaderImpl.readMap (package:hive/src/binary/binary_reader_impl.dart:212)
E/flutter (19377): #2      BinaryReaderImpl.read (package:hive/src/binary/binary_reader_impl.dart:317)
E/flutter (19377): #3      ProductAdapter.read (package:protector_app/database_models/product.g.dart:17)
E/flutter (19377): #4      BinaryReaderImpl.read (package:hive/src/binary/binary_reader_impl.dart:326)
E/flutter (19377): #5      BinaryReaderImpl.readFrame (package:hive/src/binary/binary_reader_impl.dart:274)
E/flutter (19377): #6      FrameHelper.framesFromBytes (package:hive/src/binary/frame_helper.dart:21)
E/flutter (19377): #7      FrameIoHelper.framesFromFile (package:hive/src/io/frame_io_helper.dart:42)
E/flutter (19377): <asynchronous suspension>
E/flutter (19377): #8      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:86)
E/flutter (19377): <asynchronous suspension>
E/flutter (19377): #9      HiveImpl._openBox (package:hive/src/hive_impl.dart:111)
E/flutter (19377): <asynchronous suspension>
E/flutter (19377): #10     HiveImpl.openBox (package:hive/src/hive_impl.dart:139)
E/flutter (19377): <asynchronous suspension>
E/flutter (19377): #11     HiveService.open (package:protector_app/database/hive_service.dart:42)
E/flutter (19377): <asynchronous suspension>
E/flutter (19377): #12     JSONApi.initialize (package:protector_app/networking/jsonAPI.dart:46)
E/flutter (19377): <asynchronous suspension>
E/flutter (19377): #13     main (package:protector_app/main.dart:30)
E/flutter (19377): <asynchronous suspension>
E/flutter (19377): `

And yeah I am getting the error twice. 
For the Model ich changed the naming of some fields. that's it.

Here is my code:

`import 'package:hive/hive.dart';
import 'package:path_provider/path_provider.dart' as path_provider;
import 'package:protector_app/database_models/application.dart';
import 'package:protector_app/database_models/area.dart';
import 'package:protector_app/database_models/brand_protektor.dart';
import 'package:protector_app/database_models/category.dart';
import 'package:protector_app/database_models/color.dart';
import 'package:protector_app/database_models/contact.dart';
import 'package:protector_app/database_models/material.dart';
import 'package:protector_app/database_models/news.dart';
import 'package:protector_app/database_models/news_article.dart';
import 'package:protector_app/database_models/news_imageteaser.dart';
import 'package:protector_app/database_models/product.dart';
import 'package:protector_app/database_models/reference_timestamp.dart';
import 'package:protector_app/database_models/reference.dart';
import 'package:protector_app/database_models/system_timestamp.dart';
import 'package:protector_app/database_models/system_type.dart';
import 'package:protector_app/database_models/upselling.dart';
import 'package:protector_app/database_models/user.dart';

class HiveService {
  static final HiveService _singleton = new HiveService._internal();
  HiveService._internal();

  static HiveService getInstance() => _singleton;

  bool hasConnection = false;

  initialize() async {
    await initHive();
  }

  initHive() async {
    final appDocumentDirectory =
        await path_provider.getApplicationDocumentsDirectory();
    Hive.init(appDocumentDirectory.path);
    registerAdapters();
  }

  Future<Box> open(String boxName) async {
    return await Hive.openBox(boxName);
  }

  registerAdapters() {
    Hive.registerAdapter(ProductAdapter());
    Hive.registerAdapter(BrandProtektorAdapter());
    Hive.registerAdapter(CategoryAdapter());
    Hive.registerAdapter(ColorTypeAdapter());
    Hive.registerAdapter(AreaAdapter());
    Hive.registerAdapter(ApplicationAdapter());
    Hive.registerAdapter(MaterialAdapter());
    Hive.registerAdapter(ReferenceTimestampAdapter());
    Hive.registerAdapter(ReferenceTypeAdapter());
    Hive.registerAdapter(SystemTimestampAdapter());
    Hive.registerAdapter(SystemTypeAdapter());
    Hive.registerAdapter(UpsellingTypeAdapter());
    Hive.registerAdapter(UserAdapter());
    Hive.registerAdapter(ContactAdapter());
    Hive.registerAdapter(NewsAdapter());
    Hive.registerAdapter(ArticleAdapter());
    Hive.registerAdapter(TeaserImageAdapter());
  }

  close(Box box) {
    box.close();
  }
}

class Boxes {
  static final String productsBox = 'products';
  static final String areasBox = 'areas';
  static final String appsBox = 'applications';
  static final String colorBox = 'colors';
  static final String systemTypeBox = 'systemType';
  static final String systemTimeBox = 'systemTime';
  static final String brandProtektorBox = 'brandProtektor';
  static final String referenceTypeBox = 'referenceType';
  static final String referenceTimeBox = 'referenceTime';
  static final String upsellingBox = 'upselling';
  static final String categoryTypeBox = 'categoryType';
  static final String materialBox = 'material';
  static final String ordersBox = 'sampleOrder';
  static final String userBox = 'userBox';
  static final String contactBox = 'contactBox';
  static final String newsBox = 'newsBox';
}
`

and the issue is happening when trying to open the products box (Also the model I changed was Products)
with this code:

`productBox = await _hiveService.open(Boxes.productsBox);`

**Comment by 5yearsKim** [comment]
1. typeId starts from 0, not from 1
2. delete app and restart flutter
worked for me.

**Comment by zieadshabkalieh** [comment]
for me it need just to uninstall the app and run it again <3

**Comment by radian-rgc** [comment]
Same here,
TypeId started with 0 and after need add some new field to the class, need increase typeId.
but after change the typeId to 1 i get the `Cannot read, unknown typeId: 32. Did you forget to register an adapter?` error.

```
hive: ^2.2.3
hive_flutter: ^1.1.0
```
`hive_generator: ^1.1.3`

```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Hive.initFlutter();
  Hive.registerAdapter(UserDBAdapter());
  await Hive.openBox<UserDB>('test_box');

  runApp(const MyApp());
}
```
Somebody say need just to reinstall the app, but is not right solution.

**Comment by electricen** [comment]
> ```dart
>  AuthTokenResponseModel
> ```

I encountered this problem a while ago. Before this problem occurred, I had changed the model class and ran the build runner. The box did not accept this model adapter, as I had previously recorded in the same box before the change.
solution to this problem

static Future<Box> hiveInit() async {
     await Hive.openBox('userlogin');
     await Hive.openBox('skipped');
     await Hive.openBox('lastSearched');
   }

Change the names of the boxes you have opened above in your entire project and run them again.
I hope this is the answer for you too.
good day.

**Comment by 13217300237** [comment]
> Possible solution what worked for me is to register adapters BEFORE calling `await Hive.initFlutter();`

Nice,it work for me!

**Comment by ashishdkul** [comment]
> I solved my problem by doing these **mymodel.deleteFromDisk()** you should try the same

I am facing similar issue in my app so where we need to call exactly **mymodel.deleteFromDisk()** before opening the box or after opening the box

**Comment by vkhaskina** [comment]
1. Go to C:\Users\%USERNAME%\AppData\Local\Pub\Cache\hosted\pub.dev\hive-2.2.3\test\assets\findHiveFileAndCleanUp and in all directories delete .hive and .hivec files.
2. Go to C:\Users\%USERNAME%\Documents and delete .hive and .lock files if they exist.
3. Then add await Hive.close(); await Hive.deleteFromDisk(); before ANYTHING in main.dart (WidgetsFlutterBinding.ensureInitialized(); can stay though).
4. Run flutter pub run build_runner build --delete-conflicting-outputs, flutter clean and flutter pub get/
5. The Successfully run your app!
