### ISSUE TITLE
(OS Error: Resource temporarily unavailable, errno = 35)

### ISSUE THREAD

**Issue by stevenspiel** [hivedb/hive#333]
Whenever I have concurrent tests running that use hive, I get this error:

```
FileSystemException: lock failed, path = 'test/mydb.lock' (OS Error: Resource temporarily unavailable, errno = 35)
  dart:async                                                          _asyncErrorWrapperHelper
  ...
```

Does hive support concurrency?

**Version**
 - Platform: MacOS 10.15.4
 - Flutter version: `1.12.13+hotfix.8`
 - Hive version: `1.4.1+1`
 - Hive flutter: `0.3.0+2`

**Comment by TheMisir** [comment]
You might hit resource limit on machine (file, iops, memory, process or something else). This might be because of bad software design (eg: allocating lot's of useless resources - garbage) or something I have not heard of.

Anyways, could you reproduce this issue? Also please write the code that reproduces this issue if you can.

**Comment by allansrc** [comment]
Probably has two instance of the same app running, or one running and other asking for build

**Comment by pbhuvanesh** [comment]
@stevenspiel use Hive.deleteFromDisk(); in your tearDownAll(). I had similar issues this was because multiple tests were trying to write to the same box. I think some race condition or something? My test cases are independent and I did not have to retain the box so I simply use Hive.deleteFromDisk();.

You could do something like this if you have similar issue
```
  tearDownAll((){
    Hive.deleteFromDisk();
  });
```
@TheMisir correct me if I am wrong. Thank you.

**Comment by TheMisir** [comment]
@pbhuvanesh this issue could be caused by lots of reasons. I don't think there's a "one to rule them all" solution for this.

**Comment by BaranMichal25** [comment]
I was also getting this error and in my case, it was happening because the tests were executed in parallel and they were using same directory.
I fixed it by using different path for Hive in each test file:
```dart
void main() {
  const _tag = 'XXXX'; // eg. file name

  setUp(() async {
    await initHive(_tag);
  });

  tearDown(() async {
    await cleanUpHive(_tag);
  });

// tests
}
```
and in hive_helper:
```dart
void initHive(String path) {
  Hive.init(path);
}

Future<void> cleanUpHive(String path) async {
  await Hive.close();
  final directory = File(path);
  await directory.delete(recursive: true);
}
```

**Comment by leisim** [comment]
@BaranMichal25 This is also how we do it in the Hive unit tests I believe.
