### ISSUE TITLE
Export as json Map

### ISSUE THREAD

**Issue by SteMab** [hivedb/hive#352]
**Question**
I would like to save my data in the firebase database, as well as in a hive box, then I would like ***replace the "json_serializable" library with "hive"***, but I can't convert the data in a box into a json map. In various issues and on the site<sup>[1](#note1)</sup>  it is said to use the `box.toMap()` method in this regard, however it returns a Map whose values ​​are the objects already deserialized. For example, if in my box I save instances of the following class:

```
class MyModel {
  String name;
  String code;
}
```

then `box.toMap()` return a Map with type `Map<String, MyModel>`. Instead I have to get a Map with serialized objects, as with the `_ $ MyModelToJson` method created with json_serializable.

**Version**

 - Hive version: 1.4.1+1

**Notes**:

<a name="note1">1</a>: 
From [FAQ - Can Hive sync data with a server?](https://docs.hivedb.dev/#/more/faq?id=can-hive-sync-data-with-a-server):

> Not out of the box but you can do that yourself quite easily using the box.toMap() method and the change notifier.

From [Issue  #162 - Export Database to .db / .hive /another file (csv etc)](https://github.com/hivedb/hive/issues/162#issuecomment-569458466):

> Just use yourBox.toMap() and you basically have JSON.

**Comment by TheMisir** [comment]
I suggest you to use both json_serializable and hive. Hive doesn't contains out of the box json (de)serialiation support. So you have to to it yourself (eg: using json_serialization).

Box.toMap creates key - value dictionary. It doesn't converts your objects to string -dynamic maps. You can check [source code](https://github.com/hivedb/hive/blob/master/hive/lib/src/box/box_impl.dart#L98-L105) for toMap function.

So, I just suggest you to use both packages. Because each of them has their own functionality. One is for serialization while other one is used for persistent data storage (database).

**Comment by Mabsten** [comment]
Thanks so much. The aforementioned reply in issue #162 made me doubtful. I will use hive combined with json_serializable, which I have seen work well together.

**Comment by SteMab** [comment]
Thanks so much. The aforementioned reply in [issue #162](https://github.com/hivedb/hive/issues/162#issuecomment-569458466) made me doubtful. I will use hive combined with json_serializable, which I have seen work well together.
