### ISSUE TITLE
Hive await openBox does not run before widget build

### ISSUE THREAD

**Issue by chitgoks** [hivedb/hive#358]
This is how i initialized hive.

```
  void initState() {
    super.initState();
      WidgetsBinding.instance.addPostFrameCallback((_) async {
        Directory appDocDir = await getApplicationDocumentsDirectory();
        String appDocPath = appDocDir.path;
        Hive.init(appDocPath);
        print('main');
        Global.hive = await Hive.openBox(Global.hivePath);
        print('finish hive');
      });
  }

@override
  Widget build(BuildContext context) {
    print('buildig main');
}

```
The output is
main
buildig main
finish hive

I am confused why it does not initialize hive first. i used await to make synchronous.

**Comment by dulajdanu** [comment]
Use a futurebuilder like this in the build method
  home: FutureBuilder(
        future: Hive.openBox('your_box_name'), 
        builder: (BuildContext context, AsyncSnapshot snapshot) {
          if (snapshot.connectionState == ConnectionState.done) {
            if (snapshot.hasError) {
              return Scaffold(
                body: Center(
                  child: Text(snapshot.error.toString()),
                ),
              );
            } else
              return Page1();
          } else {
            return Scaffold(
              body: Center(
                child: CircularProgressIndicator(),
              ),
            );
          }
        },
      ),

**Comment by chitgoks** [comment]
hi. yes. this is my current workaround. ill just close this .

**Comment by marcelgarus** [comment]
Btw this is intended behavior, not a workaround. Sure, calling `await` makes it "synchronous" with respect to the current scope, but you called it in `WidgetsBinding.instance.addPostFrameCallback((_) async { ... });`, so the whole thing is asynchronous again.

And that's by design.
While Hive is loading all your data into memory, you don't want to pause everything (animations, user gestures, etc.), because that would simply freeze your app / make it unresponsive. Instead, you want everything to continue normally and when Hive finished loading, display the data. That's exactly what the `FutureBuilder` does.

**Comment by chitgoks** [comment]
the WidgetsBinding.instance.addPostFrameCallback was my last try before i decided to use futurebuilder.

before that it was an ordinary method with async so it could run inside initState() but it gave the same result.

thanks for the tip!
