### ISSUE TITLE
Access hive in multiple isolates.

### ISSUE THREAD

**Issue by kalluriramkumar** [hivedb/hive#369]
Problem statement:
------------------
I am trying to access the hive in the main isolate and run the long running tasks (for instance, compaction job) in a seperate isolate. The moment hive is accessed in the child isolate, the subsequent operation to hive from the main isolate fails. This is because Hive do not support opening box in multiple isolates.

Can this be fixed? or Can anybody suggest and an approach in solving the above problem? 

Version details:
-----------------
Platform : Ubuntu 20.04
Hive Version: 1.3.0
dart version:2.8.4

**Comment by TheMisir** [comment]
This is a general multi threading related issue. You can not write to same file on different processes / threads. File needs to be closed before IO.

You can try closing boxes after you completed reading/writing stuff on main and child isolates. Some issues might occur again because of race condition. Eg.: if multiple isolates tries to open the box at same time.

Or you can send read/write tasks as message to your main isolate instead of reading it inside child isolate. Check [this SO answer](https://stackoverflow.com/a/52277743/7616528) to learn bidirectional communication in dart isolates.

**Comment by darshansatra1** [comment]
Is there any simpler solution than isolate communication?

**Comment by TheMisir** [comment]
> Is there any simpler solution than isolate communication?

Unfortunately there's not.

**Comment by darshansatra1** [comment]
@TheMisir Can you suggest to me some other DB package for multithreading?

**Comment by TheMisir** [comment]
> @TheMisir Can you suggest to me some other DB package for multithreading?

It depends on your use case. If you could tell me which data you want to share between isolates?

**Comment by darshansatra1** [comment]
So I'm running my foreground service to calculate steps. It is running perfectly when the app is closed. But when the app is running I have to calculate steps in service and also in the app as two different seperator cause foreground service is actually doing the db change in the main isolate. What I want is to calculate steps only in foreground service and that db change should also be changed in the main isolate

**Comment by TheMisir** [comment]
Depending on your data model you might try out using shared preferences. I think [objectbox-dart](https://github.com/objectbox/objectbox-dart) also supports multi threading.
