### ISSUE TITLE
Would not be it great if object insertation comes along with hive?

### ISSUE THREAD

**Issue by ujjwalbe** [hivedb/hive#413]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when i have to build the project for adding any object to database.

**Describe the solution you'd like**
 i had to do is build for typeAdapter would not be it great if it's comes prebaked? I just feels frustrated. I'm used to mongodb and feels frustrated when something is not available. Hive is good but lacks of features. 
**Describe alternatives you've considered**
null

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: 1.20.1
 - Hive version: 1.4.4

**Comment by TheMisir** [comment]
Hive requires code generation because:

Flutter does not allows runtime reflection (aka [dart:mirrors](https://api.dart.dev/stable/2.9.1/dart-mirrors/dart-mirrors-library.html)) - https://github.com/flutter/flutter/issues/1150
So hive uses compile time code generation to parse code and get metadata from dart classes/objects which is required (de)serialization. Even other packages that require serialization uses code generation method.
