### ISSUE TITLE
initFlutter: path parameter ignored?

### ISSUE THREAD

**Issue by Rayv1** [hivedb/hive#440]
**Question**
I try to seperate the boxes per User and seen that there is a parameter with initFlutter to define a subDir. 
It seems as the paramter is ignored, as the boxes are still the same and contain the same content.
I also changed the Path and restarted the App completely.

**Code sample**
```
await Hive.initFlutter("testdir");
```

**Version**
 - Platform:  Android, 
 - Flutter version: 1.20.3
 - Hive version: 1.4.4 (Hive Flutter: 0.3.1)

Am I doing something wrong or is the parameter ignored?

**Comment by TheMisir** [comment]
No, it's not ignored as you can [see here](https://github.com/hivedb/hive/blob/master/hive_flutter/lib/src/hive_extensions.dart#L13-L15).

But to change base directory you have to either restart the application to re-initialize hive which re-creates storage backend and reconfigures boxes.

Otherwise I would suggest instead of separating boxes by subdir you can add prefix/suffix to box name. For example userId.

favourites_46723423 - favourites for user with 46723423 id.

**Comment by Rayv1** [comment]
@TheMisir thanks for the suggestion. Iam going that way. I have now also seen that a restart does work and I just had the wrong user. I go with the suffix :-) Thanks
