### ISSUE TITLE
Using Hive Box in Widget Tests

### ISSUE THREAD

**Issue by adberger** [hivedb/hive#544]
**Question**
I want to do some WidgetTests for a Flutter project i'm working on.
We use Hive to store content from an API endpoint locally (caching).
The use of Hive in the app itself works, no problem after all.

But when i try to do some WidgetTests and use Hive, it fails.
The initialization of the Hive seems to work, but when i want to open a new Box the tests runs infinitely.

**Code sample**
```dart
import 'package:hive/hive.dart';
import 'package:hive_flutter/hive_flutter.dart';
...
void main() {
  testWidgets('ImpressumPage', (WidgetTester tester) async {
    await Hive.initFlutter();
    var _box = await Hive.openBox('constants');
  }
}
```

**Version**
 - Platform: Android
 - Flutter version: 1.22.3
 - Hive version: ^1.4.4+1
 - Hive_flutter version: 0.3.1

**Comment by adberger** [comment]
Anyone?

**Comment by rknell** [comment]
I'm experiencing the same issue now. DId you end up finding a solution?

**Comment by rknell** [comment]
Hey @adberger 

Ok, so the soluition has been posted in another thread.

The problem is because Hive does actual async work - ie accessing the file system etc. It needs you to call ```WidgetTester.runAsync(()=>Hive.getBox())``` as per this comment:
https://github.com/hivedb/hive/issues/386#issuecomment-664547655

I have tested it and its working for me.

The docs on runAsync provide more clarity:
https://api.flutter.dev/flutter/flutter_test/WidgetTester/runAsync.html

**Comment by adberger** [comment]
Thanks for the response.
Unfortunately I no longer work for the project, so I can't test this suggested solution.
So I will close this issue for now, thanks.
