### ISSUE TITLE
Need to know about active development.

### ISSUE THREAD

**Issue by askprateek** [hivedb/hive#55]
**Question**
What are your plans for maintaining this package? We are thinking of using Hive in our production app. We want to know if you will be maintaining Hive actively.

**Comment by leisim** [comment]
I'm very dedicated to this project and I plan to maintain it over a long period of time since I think Hive will become very popular once Flutter web & desktop are stable.

If I should not be able to continue development for some unforeseeable reason, I will give the project to the [Flutter Community](https://github.com/fluttercommunity).
