### ISSUE TITLE
The method 'listenable' isn't defined for the type 'Box'.

### ISSUE THREAD

**Issue by JAICHANGPARK** [hivedb/hive#598]
**Question**
The method 'listenable' isn't defined for the type 'Box'.

**Code sample**
```dart
return ValueListenableBuilder(valueListenable: Hive.box('settings').listenable(), builder: builder)
```

**Version**
 - Platform: Android,
 - Flutter version: 2.1.0
 - Hive version: 2.0.0

**Comment by TheMisir** [comment]
I think you have to import `package:hive_flutter/hive_flutter.dart'`

**Comment by thegoldgoat** [comment]
> I think you have to import `package:hive_flutter/hive_flutter.dart'`

Can confirm that this works :)

**Comment by mbaumgartenbr** [comment]
Hey @TheMisir a lot of people get this same error, what if you added the listenable extension to the hive.dart package with an empty "throw" body and annotate it with `@Deprecated('You must import hive_flutter to access listenable')`.

**Comment by TheMisir** [comment]
> Hey @TheMisir a lot of people get this same error, what if you added the listenable extension to the hive.dart package with an empty "throw" body and annotate it with `@Deprecated('You must import hive_flutter to access listenable')`.
> 
> Edit: now that i think of it, if you do that, and the user imported both libraries, you would have to `import 'hive' hide Extension;`, perhaps hive_flutter should export hive hiding extension then?

But,

1. Value notifier is part of flutter sdk, not dart. So we couldn't define `ValueListenable<T>` variable.

2. I don't think extensions are capable of overriding methods.

**Comment by mbaumgartenbr** [comment]
Use just void listenable(), it should not work at all, it's just to warn the user to import hive_flutter.

The overriding is an issue, but hive_flutter could export hive hiding the hive fail extension as we always need to import hive when importing hive_flutter.

Or am I missing something? Is there a use case where we import hive_flutter without hive?

**Comment by TheMisir** [comment]
> Use just void listenable(), it should not work at all, it's just to warn the user to import hive_flutter.

Then, when you call `listen()`, the deprecated one will be resolved and executed every time.

<img width="1001" alt="Screen Shot 2021-05-20 at 9 32 34 PM" src="https://user-images.githubusercontent.com/29130291/119023562-240c4300-b9b3-11eb-8f64-85019acca9bc.png">

**Comment by mbaumgartenbr** [comment]
It's probably not a good solution because everyone using hive with flutter would have to remove the hive import, but have a look:

It's probably not worth adding this, but I just wanted to explain what I had in mind so I don't sound crazy lol

Add the extension:

![extension_on_hive](https://user-images.githubusercontent.com/58597459/119032070-273b0b00-b982-11eb-9da1-366eb07689c6.png)

Only importing hive:

![deprecated](https://user-images.githubusercontent.com/58597459/119032149-3c179e80-b982-11eb-9232-a69c4f25f8df.png)

Export hive from hive_flutter (hiding the broken extension), as you always need hive when using hive_flutter:

![export_hive](https://user-images.githubusercontent.com/58597459/119032206-4d60ab00-b982-11eb-80e7-e0aa2068c78f.png)

Error importing both:

![error_importing_both](https://user-images.githubusercontent.com/58597459/119032108-30c47300-b982-11eb-975f-b0c52e51e596.png)

Correct usage "not importing hive by it self when working with flutter":

![correct_usage](https://user-images.githubusercontent.com/58597459/119032593-be07c780-b982-11eb-828c-167d75f935cf.png)

**Comment by TheMisir** [comment]
> Correct usage "not importing hive by itself when working with flutter":

That's the part actually I'm concerned about. I don't want to mess around with exists code. I would rather want to make hive stable instead of making breaking changes. Because getting random errors out of nowhere after upgrading your dependencies is not fun.

Instead of adding deprecated listenable to `hive`, exporting `hive` from `hive_flutter` would make more sense.

**Comment by thegoldgoat** [comment]
> I would rather want to make hive stable instead of making breaking changes

Yeah, I agree. That's a pity since the `@Deprecated` idea wad good

**Comment by mbaumgartenbr** [comment]
> > Correct usage "not importing hive by itself when working with flutter":
> 
> That's the part actually I'm concerned about. I don't want to mess around with exists code. I would rather want to make hive stable instead of making breaking changes. Because getting random errors out of nowhere after upgrading your dependencies is not fun.
> 
> Instead of adding deprecated listenable to `hive`, exporting `hive` from `hive_flutter` would make more sense.

The bummer is that new users that only import hive will get this error and keep filing the same issue :confused:

**Comment by TheMisir** [comment]
@mbaumgartenbr 

You're right 😕 Maybe we have to update docs to point out importing hive_flutter is required to execute `listenable()` method. Or we can somehow encourage them to use `hive_flutter` only, after publishing #670 patch.

**Comment by thegoldgoat** [comment]
Not an expert of Flutter however here's what I though:

As far as I understood the problem would be that 'hive' package doesn't have `ValueListenable<T>` since it is dependent on Flutter SDK. Is there a way in Dart to create a 'not implemented' class like in C++, something like this:

```dart

// Declare not implemented class
class ValueListenable<T>;

class Box<T> {
  @Deprecated('...')
  ValueListenable<T> listenable() => throw Exception();
}

```

And maybe, like C++, ValueListenable<T> can be implemented elsewhere

**Comment by TheMisir** [comment]
> Not an expert of Flutter however here's what I though:
> 
> As far as I understood the problem would be that 'hive' package doesn't have `ValueListenable<T>` since it is dependent on Flutter SDK. Is there a way in Dart to create a 'not implemented' class like in C++, something like this:
> 
> ```dart
> // Declare not implemented class
> class ValueListenable<T>;
> 
> class Box<T> {
>   @Deprecated('...')
>   ValueListenable<T> listenable() => throw Exception();
> }
> ```
> 
> And maybe, like C++, ValueListenable can be implemented elsewhere

Actually it's more than that. If we implement Box.listenable on both `hive` and `hive_flutter`, when you import both libraries there will be conflicting issues.

```dart
import 'package:hive/hive.dart';
import 'package:hive_flutter/hive_flutter.dart';

void main() {
  Hive.box('mybox').listenable();
}
```

In that case, which `.listenable()` implementation would compiler use. In a world where compiler uses `hive_flutter` implementation, everything will be alright. But if it uses `hive`'s implementation or even worse one of them depending on random factors, that would make things even worse and unpredictable.

**Comment by thegoldgoat** [comment]
Mhh I see, then I guess explicitly stating to import 'hive_flutter' in the docs is the easiest way :)

For example I would add it in [this](https://docs.hivedb.dev/#/tutorials/favorite_books?id=myapp-widget) section

**Comment by TheMisir** [comment]
Closing this one since this is not really an issue / bug.
