### ISSUE TITLE
What are the benefits of using multiple boxes?

### ISSUE THREAD

**Issue by marcelgarus** [hivedb/hive#87]
I have an app with loads of entities with unique IDs but different types. Now I can either store all of them into a single box, or into different boxes depending on their type.
Are there any benefits of choosing one option over the other apart from having more control about when items of a particular type are loaded into memory? Like, is there a maximum box size or something like that?

**Comment by leisim** [comment]
Not really. Multiple boxes can write in parallel but that is not a big advantage since you don't have to await write operations anyway.

When queries are supported, they will be faster when performed on fewer entries.

**Comment by marcelgarus** [comment]
Okay great, thanks 😊

**Comment by nioncode** [comment]
I was also thinking about this recently. In my case, I want to mostly store instances of the same type to cache them locally, but additionally, I want to store some global state that belongs to the entire list of entries (like a flag to store if everything is up-to-date and the last cached response ETag from the server). So I basically want to store `List<SomeObject>`, a `bool`, and a `String`.

At first, I used two separate boxes, `Box<SomeObject> objects` and `Box<dynamic> globalState`. I think the only benefit of using separate boxes is that you get type safety and things like `box.values.where()` get simpler, since you don't have to check the type.

However, since it feels a bit awkward to handle two boxes, I'm now thinking of merging everything into the same box. The big downside here is that the `listenable` method returns a `Box` and not a `Box<SomeObject>`, so the ui also has to cast the box.

What did you choose in the end @marcelgarus and did you find any other quirks with it?

**Comment by marcelgarus** [comment]
When I created this issue I believe there were no typed boxes yet, so I didn't have the disadvantage of types not matching.
Right now, it's working fine. That being said, for my use case, I only need to retrieve items by their id, not by type or filter criteria so I'm not sure how much boilerplate this adds to the UI logic if you need this functionality.
I recommend coding up a small prototype and seeing if the code looks fine.
