### ISSUE TITLE
when will there be a new version??

### ISSUE THREAD

**Issue by fisforfaheem** [hivedb/hive#911]
it been 3 months now

**Comment by themisir** [comment]
Please use issue tracker for reporting bugs or proposing new features. I personally don't like pushing updates just sake of keeping it up to date. We provide necessary patches when needed, including bug fixes or requested features. Some feature implementations or bug fixes takes long time to get done because:

1. Bugs can be sometimes hard to catch...
2. We prefer to keep hive API as stable as possible, by avoiding breaking changes, implementing new features takes some time so we can discuss what's "best" way to solve some problems. eg: #804 

I hope that explains current situation :) Please let us know if you have any specific issue or feature requirement.
